"""Generate synthetic test structures with known ground truth.

Builds an idealised protein backbone from scratch (N-CA-C, ideal bond geometry,
specified phi/psi), then derives a set of variants in which the perturbation is
known exactly -- a 2.5 A rigid shift of residues 20-26, a 60 degree torsion kink
at residue 30, and so on.

That known ground truth is the point. Real structures cannot tell you whether
the pipeline found the right answer; these can. tests/test_pipeline.py asserts
that StructScan recovers each planted perturbation.

    python tools/make_synthetic.py
    python tools/make_synthetic.py --outdir /tmp/fixtures --length 80
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

# Ideal backbone geometry (angstroms / degrees).
BOND_N_CA = 1.458
BOND_CA_C = 1.525
BOND_C_N = 1.329
ANGLE_N_CA_C = 111.2
ANGLE_CA_C_N = 116.2
ANGLE_C_N_CA = 121.7
OMEGA = 180.0

# (phi, psi) for common secondary structure.
HELIX = (-57.0, -47.0)
SHEET = (-139.0, 135.0)
COIL = (-90.0, 120.0)

RESIDUE_CYCLE = ("ALA", "LEU", "GLY", "VAL", "SER", "THR", "ILE", "LYS", "GLU", "ASP")

DEFAULT_SEED = 20240517


def _place(a: np.ndarray, b: np.ndarray, c: np.ndarray,
           bond_length: float, bond_angle: float, torsion: float) -> np.ndarray:
    """Natural-extension-reference-frame placement of a fourth atom.

    Angles in radians. Returns the position of D given A-B-C and the internal
    coordinates (|CD|, angle BCD, torsion ABCD).
    """
    bc = c - b
    bc = bc / np.linalg.norm(bc)
    n = np.cross(b - a, bc)
    norm_n = np.linalg.norm(n)
    if norm_n < 1e-8:  # collinear seed; nudge to keep the frame well defined
        n = np.cross(bc, np.array([0.0, 0.0, 1.0]))
        norm_n = np.linalg.norm(n)
    n = n / norm_n
    frame = np.array([bc, np.cross(n, bc), n])
    offset = np.array([
        -bond_length * np.cos(bond_angle),
        bond_length * np.sin(bond_angle) * np.cos(torsion),
        bond_length * np.sin(bond_angle) * np.sin(torsion),
    ])
    return c + offset.dot(frame)


def build_backbone(torsions: Sequence[Tuple[float, float]]) -> List[Dict[str, np.ndarray]]:
    """Build an N-CA-C backbone from a list of (phi, psi) pairs, in degrees."""
    rad = np.radians
    residues: List[Dict[str, np.ndarray]] = []

    # Seed the first residue in the xy-plane.
    n0 = np.zeros(3)
    ca0 = np.array([BOND_N_CA, 0.0, 0.0])
    theta = np.pi - rad(ANGLE_N_CA_C)
    c0 = ca0 + BOND_CA_C * np.array([np.cos(theta), np.sin(theta), 0.0])
    residues.append({"N": n0, "CA": ca0, "C": c0})

    for index in range(1, len(torsions)):
        prev = residues[-1]
        psi_prev = torsions[index - 1][1]
        phi_curr = torsions[index][0]

        n = _place(prev["N"], prev["CA"], prev["C"],
                   BOND_C_N, rad(ANGLE_CA_C_N), rad(psi_prev))
        ca = _place(prev["CA"], prev["C"], n,
                    BOND_N_CA, rad(ANGLE_C_N_CA), rad(OMEGA))
        c = _place(prev["C"], n, ca,
                   BOND_CA_C, rad(ANGLE_N_CA_C), rad(phi_curr))
        residues.append({"N": n, "CA": ca, "C": c})

    return residues


def default_torsions(length: int) -> List[Tuple[float, float]]:
    """A mixed helix / coil / sheet topology, so the fold is not uniform."""
    torsions: List[Tuple[float, float]] = []
    for i in range(length):
        fraction = i / max(1, length - 1)
        if fraction < 0.30:
            torsions.append(HELIX)
        elif fraction < 0.42:
            torsions.append(COIL)
        elif fraction < 0.70:
            torsions.append(HELIX)
        elif fraction < 0.80:
            torsions.append(COIL)
        else:
            torsions.append(SHEET)
    return torsions


def rotation_matrix(alpha: float, beta: float, gamma: float) -> np.ndarray:
    """Z-Y-X Euler rotation, angles in degrees."""
    a, b, g = np.radians([alpha, beta, gamma])
    rz = np.array([[np.cos(a), -np.sin(a), 0], [np.sin(a), np.cos(a), 0], [0, 0, 1]])
    ry = np.array([[np.cos(b), 0, np.sin(b)], [0, 1, 0], [-np.sin(b), 0, np.cos(b)]])
    rx = np.array([[1, 0, 0], [0, np.cos(g), -np.sin(g)], [0, np.sin(g), np.cos(g)]])
    return rz @ ry @ rx


def write_pdb(path: Path, residues: List[Dict[str, np.ndarray]],
              res_names: Sequence[str], chain: str = "A",
              start_resseq: int = 1, skip: Optional[Sequence[int]] = None) -> None:
    """Write N/CA/C backbone atoms as a minimal but standards-conformant PDB."""
    skip_set = set(skip or ())
    path.parent.mkdir(parents=True, exist_ok=True)
    serial = 1
    lines = [
        "REMARK   1 SYNTHETIC STRUCTURE GENERATED BY STRUCTSCAN tools/make_synthetic.py",
        "REMARK   1 IDEALISED N-CA-C BACKBONE; NOT AN EXPERIMENTAL STRUCTURE",
    ]
    for index, residue in enumerate(residues):
        resseq = start_resseq + index
        if resseq in skip_set:
            continue
        res_name = res_names[index % len(res_names)]
        for atom_name in ("N", "CA", "C"):
            x, y, z = residue[atom_name]
            lines.append(
                f"ATOM  {serial:5d} {atom_name:^4s}{'':1s}{res_name:>3s} "
                f"{chain:1s}{resseq:4d}{'':1s}   "
                f"{x:8.3f}{y:8.3f}{z:8.3f}{1.00:6.2f}{20.00:6.2f}"
                f"          {atom_name[0]:>2s}"
            )
            serial += 1
    lines.append("TER")
    lines.append("END")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _shift_window(residues: List[Dict[str, np.ndarray]], first: int, last: int,
                  vector: np.ndarray, start_resseq: int = 1) -> List[Dict[str, np.ndarray]]:
    """Rigidly translate residues [first, last] by ``vector`` (resseq numbering)."""
    out = []
    for index, residue in enumerate(residues):
        resseq = start_resseq + index
        if first <= resseq <= last:
            out.append({k: v + vector for k, v in residue.items()})
        else:
            out.append({k: v.copy() for k, v in residue.items()})
    return out


def _add_noise(residues: List[Dict[str, np.ndarray]], sigma: float,
               rng: np.random.Generator) -> List[Dict[str, np.ndarray]]:
    return [
        {k: v + rng.normal(0.0, sigma, size=3) for k, v in residue.items()}
        for residue in residues
    ]


def _transform(residues: List[Dict[str, np.ndarray]], rotation: np.ndarray,
               translation: np.ndarray) -> List[Dict[str, np.ndarray]]:
    return [
        {k: rotation @ v + translation for k, v in residue.items()}
        for residue in residues
    ]


def generate(outdir: Path, length: int = 60, seed: int = DEFAULT_SEED) -> Dict[str, object]:
    """Write the reference plus the variant battery. Returns the manifest."""
    rng = np.random.default_rng(seed)
    outdir = Path(outdir)
    variants_dir = outdir / "variants"
    variants_dir.mkdir(parents=True, exist_ok=True)

    torsions = default_torsions(length)
    reference = build_backbone(torsions)
    res_names = [RESIDUE_CYCLE[i % len(RESIDUE_CYCLE)] for i in range(length)]

    reference_path = outdir / "wildtype_reference.pdb"
    write_pdb(reference_path, reference, res_names)

    manifest: Dict[str, object] = {
        "reference": reference_path.name,
        "length": length,
        "seed": seed,
        "variants": {},
    }

    def record(name: str, residues, expect: Dict[str, object],
               names: Optional[Sequence[str]] = None,
               skip: Optional[Sequence[int]] = None) -> None:
        write_pdb(variants_dir / f"{name}.pdb", residues, names or res_names, skip=skip)
        manifest["variants"][name] = expect

    # 1. Essentially identical: coordinate noise only.
    record(
        "v01_stable",
        _add_noise(reference, 0.03, rng),
        {"kind": "noise", "expect_tag": "Stable", "hotspot_residues": []},
    )

    # 2. Localised loop displacement.
    record(
        "v02_loop_shift_20_26",
        _shift_window(reference, 20, 26, np.array([2.5, 0.0, 0.0])),
        {"kind": "rigid_window_shift", "expect_tag": "High Priority Hotspot",
         "window": [20, 26], "magnitude": 2.5,
         "hotspot_residues": list(range(20, 27))},
    )

    # 3. Larger displacement over a different window.
    record(
        "v03_core_shift_40_48",
        _shift_window(reference, 40, 48, np.array([0.0, 5.0, 0.0])),
        {"kind": "rigid_window_shift", "expect_tag": "High Priority Hotspot",
         "window": [40, 48], "magnitude": 5.0,
         "hotspot_residues": list(range(40, 49))},
    )

    # 4. Mobile C-terminus -- the case --trim-outliers exists for.
    record(
        "v04_terminal_flex",
        _shift_window(reference, length - 5, length, np.array([0.0, 0.0, 4.0])),
        {"kind": "terminal_shift", "expect_tag": "High Priority Hotspot",
         "window": [length - 5, length], "magnitude": 4.0,
         "hotspot_residues": list(range(length - 5, length + 1))},
    )

    # 5. Backbone torsion kink: rebuild with phi/psi altered at one residue.
    kink_index = 29  # zero-based -> resseq 30
    kinked = list(torsions)
    kinked[kink_index] = (torsions[kink_index][0] + 60.0, torsions[kink_index][1] - 60.0)
    record(
        "v05_dihedral_kink_30",
        build_backbone(kinked),
        {"kind": "torsion", "expect_tag": "High Priority Hotspot",
         "kink_resseq": kink_index + 1, "delta_degrees": 60.0,
         "hotspot_residues": [kink_index + 1]},
    )

    # 6. Rigid-body move only: superposition must reduce this to ~zero.
    record(
        "v06_rigid_body",
        _transform(reference, rotation_matrix(37.0, -21.0, 64.0),
                   np.array([12.0, -8.0, 30.0])),
        {"kind": "rigid_body", "expect_tag": "Stable", "hotspot_residues": [],
         "note": "identical structure, moved in space; RMSD must be ~0"},
    )

    # 7. Missing residues: gap tolerance.
    record(
        "v07_gapped",
        _add_noise(reference, 0.03, rng),
        {"kind": "gap", "expect_tag": "Stable", "missing": list(range(10, 15)),
         "hotspot_residues": [],
         "note": "residues 10-14 deleted; must still align on the remainder"},
        skip=range(10, 15),
    )

    # 8. Residue substitutions with unchanged coordinates.
    substituted = list(res_names)
    for position in (15, 33, 50):
        substituted[position - 1] = "TRP"
    record(
        "v08_substitutions",
        _add_noise(reference, 0.03, rng),
        {"kind": "substitution", "expect_tag": "Stable",
         "substituted_resseq": [15, 33, 50], "hotspot_residues": []},
        names=substituted,
    )

    manifest_path = outdir / "ground_truth.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate synthetic structures with known perturbations."
    )
    parser.add_argument("--outdir", type=Path,
                        default=Path(__file__).resolve().parents[1] / "data")
    parser.add_argument("--length", type=int, default=60, help="residues in the backbone")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    args = parser.parse_args(argv)

    manifest = generate(args.outdir, length=args.length, seed=args.seed)
    print(f"reference -> {args.outdir / 'wildtype_reference.pdb'}")
    print(f"variants  -> {args.outdir / 'variants'} ({len(manifest['variants'])} files)")
    for name, expect in manifest["variants"].items():
        print(f"    {name:<24} {expect['kind']:<20} expect: {expect['expect_tag']}")
    print(f"manifest  -> {args.outdir / 'ground_truth.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
